version: "3.7"
services:
  mealie:
    image: ghcr.io/mealie-recipes/mealie:latest
    container_name: mealie
    restart: unless-stopped
    ports:
      - "9000:9000"
    environment:
      - ALLOW_SIGNUP=false
      - TZ=America/Los_Angeles
      - BASE_URL=https://spring-prep-hike-production.up.railway.app
      - CORS_ORIGINS=*
    volumes:
      - mealie-data:/app/data

volumes:
  mealie-data:
